modLoader="javafml"
loaderVersion="[37,)"
license="GPL3"

[[mods]]
modId="posture"
version="1.0.0"
displayName="Posture"
updateJSONURL="https://mrcrayfish.com/modupdatejson?id=posture"
displayURL="https://mrcrayfish.com/mods?id=posture"
logoFile="posture.png"
authors="MrCrayfish"
description="A compatibility library allowing developers to manipulate the player model safely"

[[dependencies.posture]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.109,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.posture]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
